-- ====================================================================
-- HCM-SMS SUPABASE POSTGRESQL SCHEMA & SECURITY BLUEPRINT
-- Target: Supabase Cloud Database (Multi-Device Sync Architecture)
-- Project URL: https://wsyljsocuvrzhmdcygcu.supabase.co
-- ====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. AUTOMATIC UPDATED_AT TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ====================================================================
-- 3. CORE SYSTEM & USER TABLES
-- ====================================================================

-- Users / User Accounts Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'TEACHER',
    email TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_login_timestamp BIGINT DEFAULT NULL,
    last_logout_timestamp BIGINT DEFAULT NULL,
    must_change_password BOOLEAN DEFAULT FALSE,
    failed_login_attempts INT DEFAULT 0,
    is_deleted BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_users_updated_at BEFORE UPDATE ON public.users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- School Settings Table
CREATE TABLE IF NOT EXISTS public.school_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    school_name_en TEXT DEFAULT 'Harvest Christian Academy',
    school_name_my TEXT DEFAULT '',
    motto TEXT DEFAULT 'Faith, Excellence, Leadership',
    address TEXT DEFAULT 'Yangon, Myanmar',
    phone TEXT DEFAULT '+95 9 123 456 789',
    email TEXT DEFAULT 'info@hcm.edu.mm',
    website TEXT DEFAULT 'www.hcm.edu.mm',
    principal_name TEXT DEFAULT 'Dr. Aung San',
    logo_path TEXT DEFAULT '',
    current_academic_year TEXT DEFAULT '2025-2026',
    system_notifications_enabled BOOLEAN DEFAULT TRUE,
    backup_reminders_enabled BOOLEAN DEFAULT TRUE,
    academic_year_reminder_enabled BOOLEAN DEFAULT TRUE,
    assessment_reminder_enabled BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_school_settings_updated_at BEFORE UPDATE ON public.school_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ====================================================================
-- 4. ACADEMICS & CURRICULUM TABLES
-- ====================================================================

-- Grades / Standards Table
CREATE TABLE IF NOT EXISTS public.grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    grade_name TEXT NOT NULL,
    education_level TEXT NOT NULL,
    report_card_template TEXT DEFAULT 'Standard',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_grades_updated_at BEFORE UPDATE ON public.grades
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- School Classes / Sections Table
CREATE TABLE IF NOT EXISTS public.school_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    grade_id BIGINT REFERENCES public.grades(id) ON DELETE CASCADE,
    class_name TEXT NOT NULL,
    capacity INT DEFAULT 40,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_school_classes_updated_at BEFORE UPDATE ON public.school_classes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Subjects Table
CREATE TABLE IF NOT EXISTS public.subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    subject_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    sub_track TEXT DEFAULT '',
    is_enabled BOOLEAN DEFAULT TRUE,
    is_editable BOOLEAN DEFAULT TRUE,
    is_custom BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_subjects_updated_at BEFORE UPDATE ON public.subjects
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Grade Subject Cross Reference Table
CREATE TABLE IF NOT EXISTS public.grade_subject_cross_ref (
    grade_id BIGINT REFERENCES public.grades(id) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
    PRIMARY KEY (grade_id, subject_id)
);

-- Assessment Types Table
CREATE TABLE IF NOT EXISTS public.assessment_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    name TEXT NOT NULL,
    education_level TEXT NOT NULL,
    is_custom BOOLEAN DEFAULT FALSE,
    is_enabled BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_assessment_types_updated_at BEFORE UPDATE ON public.assessment_types
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Custom Exams Table
CREATE TABLE IF NOT EXISTS public.custom_exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    grade_id BIGINT DEFAULT 0,
    exam_name TEXT NOT NULL,
    is_enabled BOOLEAN DEFAULT TRUE,
    description TEXT DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_custom_exams_updated_at BEFORE UPDATE ON public.custom_exams
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Grading Policies Table
CREATE TABLE IF NOT EXISTS public.grading_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    education_level TEXT NOT NULL,
    subject_name TEXT NOT NULL,
    max_mark INT DEFAULT 100,
    pass_mark INT DEFAULT 40,
    distinction_mark INT DEFAULT 75,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_grading_policies_updated_at BEFORE UPDATE ON public.grading_policies
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ====================================================================
-- 5. PEOPLE (STUDENTS & TEACHERS) TABLES
-- ====================================================================

-- Students Table
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    student_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    grade TEXT NOT NULL,
    class_name TEXT NOT NULL,
    gender TEXT NOT NULL,
    date_of_birth TEXT NOT NULL,
    parent_name TEXT NOT NULL,
    parent_phone TEXT NOT NULL,
    address TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    photo_avatar_index INT DEFAULT 0,
    stream TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_students_updated_at BEFORE UPDATE ON public.students
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Teachers Table
CREATE TABLE IF NOT EXISTS public.teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    teacher_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT DEFAULT '',
    assigned_grade TEXT DEFAULT 'KG',
    assigned_class TEXT DEFAULT 'A',
    assigned_subjects TEXT DEFAULT 'Myanmar, English',
    employment_status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_teachers_updated_at BEFORE UPDATE ON public.teachers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ====================================================================
-- 6. ASSESSMENTS & MARKS TABLES
-- ====================================================================

-- Assessments Table
CREATE TABLE IF NOT EXISTS public.assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    title TEXT NOT NULL,
    grade TEXT NOT NULL,
    subject TEXT NOT NULL,
    assessment_type TEXT NOT NULL,
    assessment_period TEXT DEFAULT 'Monthly',
    academic_year TEXT DEFAULT '2025-2026',
    max_marks DOUBLE PRECISION DEFAULT 100.0,
    date_conducted TEXT NOT NULL,
    description TEXT DEFAULT '',
    status TEXT DEFAULT 'DRAFT',
    created_by TEXT DEFAULT 'Admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_assessments_updated_at BEFORE UPDATE ON public.assessments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Student Marks Table
CREATE TABLE IF NOT EXISTS public.student_marks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    assessment_id BIGINT REFERENCES public.assessments(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    marks_obtained DOUBLE PRECISION NOT NULL,
    is_absent BOOLEAN DEFAULT FALSE,
    is_exempt BOOLEAN DEFAULT FALSE,
    is_passed BOOLEAN DEFAULT FALSE,
    is_distinction BOOLEAN DEFAULT FALSE,
    remarks TEXT DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_by TEXT DEFAULT 'Teacher',
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_student_marks_updated_at BEFORE UPDATE ON public.student_marks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Assessment Results Table
CREATE TABLE IF NOT EXISTS public.assessment_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    assessment_period TEXT NOT NULL,
    academic_year TEXT NOT NULL,
    grade TEXT NOT NULL,
    class_name TEXT NOT NULL,
    total_marks DOUBLE PRECISION DEFAULT 0.0,
    max_possible_marks DOUBLE PRECISION DEFAULT 0.0,
    percentage DOUBLE PRECISION DEFAULT 0.0,
    overall_result TEXT DEFAULT 'Pending',
    distinction_count INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_assessment_results_updated_at BEFORE UPDATE ON public.assessment_results
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ====================================================================
-- 7. HCM HOLISTIC ASSESSMENT & SGI TABLES
-- ====================================================================

-- Holistic Categories Table
CREATE TABLE IF NOT EXISTS public.holistic_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    domain TEXT NOT NULL,
    category_name TEXT NOT NULL,
    description TEXT DEFAULT '',
    max_stars INT DEFAULT 5,
    is_enabled BOOLEAN DEFAULT TRUE,
    is_default BOOLEAN DEFAULT FALSE,
    order_index INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_holistic_categories_updated_at BEFORE UPDATE ON public.holistic_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Holistic Results Table
CREATE TABLE IF NOT EXISTS public.holistic_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES public.holistic_categories(id) ON DELETE CASCADE,
    assessment_period TEXT NOT NULL,
    academic_year TEXT NOT NULL,
    rating_stars INT DEFAULT 0,
    max_stars INT DEFAULT 5,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_by TEXT DEFAULT 'Teacher',
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_holistic_results_updated_at BEFORE UPDATE ON public.holistic_results
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- SGI Categories Table
CREATE TABLE IF NOT EXISTS public.sgi_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    category_name TEXT NOT NULL,
    description TEXT DEFAULT '',
    max_stars INT DEFAULT 5,
    is_enabled BOOLEAN DEFAULT TRUE,
    order_index INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_sgi_categories_updated_at BEFORE UPDATE ON public.sgi_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- SGI Results Table
CREATE TABLE IF NOT EXISTS public.sgi_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES public.sgi_categories(id) ON DELETE CASCADE,
    assessment_period TEXT NOT NULL,
    academic_year TEXT NOT NULL,
    rating_stars INT DEFAULT 0,
    max_stars INT DEFAULT 5,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_by TEXT DEFAULT 'Teacher',
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_sgi_results_updated_at BEFORE UPDATE ON public.sgi_results
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Teacher Comments Table
CREATE TABLE IF NOT EXISTS public.teacher_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    assessment_period TEXT NOT NULL,
    academic_year TEXT NOT NULL,
    strength_comment TEXT DEFAULT '',
    need_improvement_comment TEXT DEFAULT '',
    general_comment TEXT DEFAULT '',
    future_recommendation TEXT DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_by TEXT DEFAULT 'Teacher',
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_teacher_comments_updated_at BEFORE UPDATE ON public.teacher_comments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ====================================================================
-- 8. PERIODS, ATTENDANCE & PROMOTION TABLES
-- ====================================================================

-- Assessment Periods Table
CREATE TABLE IF NOT EXISTS public.assessment_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    period_name TEXT NOT NULL,
    education_level TEXT NOT NULL,
    period_category TEXT DEFAULT '',
    is_enabled BOOLEAN DEFAULT TRUE,
    order_index INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_assessment_periods_updated_at BEFORE UPDATE ON public.assessment_periods
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Attendance Records Table
CREATE TABLE IF NOT EXISTS public.attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    academic_year TEXT NOT NULL,
    grade TEXT NOT NULL,
    class_name TEXT NOT NULL,
    status TEXT NOT NULL,
    recorded_by TEXT DEFAULT 'Teacher',
    recorded_date_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_attendance_records_updated_at BEFORE UPDATE ON public.attendance_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Academic Years Table
CREATE TABLE IF NOT EXISTS public.academic_years (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    year_name TEXT UNIQUE NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    status TEXT DEFAULT 'UPCOMING',
    is_current_active BOOLEAN DEFAULT FALSE,
    closed_date BIGINT DEFAULT 0,
    closed_by TEXT DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_academic_years_updated_at BEFORE UPDATE ON public.academic_years
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Promotion History Table
CREATE TABLE IF NOT EXISTS public.promotion_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    from_academic_year TEXT NOT NULL,
    to_academic_year TEXT NOT NULL,
    from_grade TEXT NOT NULL,
    to_grade TEXT NOT NULL,
    from_class TEXT NOT NULL,
    to_class TEXT NOT NULL,
    action_type TEXT NOT NULL,
    promoted_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    promoted_by TEXT DEFAULT 'Admin',
    remarks TEXT DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_dirty BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TRIGGER set_promotion_history_updated_at BEFORE UPDATE ON public.promotion_history
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ====================================================================
-- 9. INDEXES FOR PERFORMANCE OPTIMIZATION
-- ====================================================================

CREATE INDEX IF NOT EXISTS idx_students_grade_class ON public.students(grade, class_name);
CREATE INDEX IF NOT EXISTS idx_assessments_grade_subject ON public.assessments(grade, subject);
CREATE INDEX IF NOT EXISTS idx_student_marks_assessment_student ON public.student_marks(assessment_id, student_id);
CREATE INDEX IF NOT EXISTS idx_holistic_results_student ON public.holistic_results(student_id, assessment_period);
CREATE INDEX IF NOT EXISTS idx_attendance_student_date ON public.attendance_records(student_id, date);

-- ====================================================================
-- 10. ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grade_subject_cross_ref ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grading_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_marks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holistic_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holistic_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sgi_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sgi_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.academic_years ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_history ENABLE ROW LEVEL SECURITY;

-- Allow authenticated and anon (using key) access for full sync capability
DO $$ 
DECLARE 
    tbl text;
BEGIN
    FOR tbl IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema='public' AND table_type='BASE TABLE'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Allow anon and auth sync on %I" ON public.%I', tbl, tbl);
        EXECUTE format('CREATE POLICY "Allow anon and auth sync on %I" ON public.%I FOR ALL USING (true) WITH CHECK (true);', tbl, tbl);
    END LOOP;
END $$;

-- ====================================================================
-- 11. SUPABASE STORAGE BUCKET CONFIGURATION
-- ====================================================================

INSERT INTO storage.buckets (id, name, public) 
VALUES ('school_assets', 'school_assets', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Read Access for School Assets"
ON storage.objects FOR SELECT
USING (bucket_id = 'school_assets');

CREATE POLICY "Authenticated Upload Access for School Assets"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'school_assets');

CREATE POLICY "Authenticated Update Access for School Assets"
ON storage.objects FOR UPDATE
USING (bucket_id = 'school_assets');
